module Magic
	module Decorator
		class Base
			extend Lookup

			def decorated?: -> bool

			private

			def self.undecorated:      (interned)  -> Symbol
					| (interned, interned, *interned)  -> Array[Symbol]
					|                (Array[interned]) -> Array[Symbol]
		end
	end
end
